server:
  port: 0

spring:
  application:
    name: order-service
  
mybatis:
  config-location: classpath:mybatis-config.xml

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.kbank.orderservice: DEBUG
