select * from tb_cust_white_list;

create table users (
    id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    email VARCHAR2(50) NOT NULL,
    name VARCHAR2(50) NOT NULL,
    user_id VARCHAR2(200) NOT NULL,
    encrypted_pwd VARCHAR2(200) NOT NULL,
    CONSTRAINT email_unique UNIQUE (email),
    CONSTRAINT user_id_unique UNIQUE (user_id),
    CONSTRAINT encrypted_pwd_unique UNIQUE (encrypted_pwd)
);

create table catalog (
    id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    created_at DATE DEFAULT CURRENT_DATE NOT NULL,
    product_id VARCHAR2(100) NOT NULL,
    product_name VARCHAR2(100) NOT NULL,
    stock NUMBER NOT NULL,
    unit_price NUMBER NOT NULL,
    CONSTRAINT product_id_unique UNIQUE (product_id)
);

create table orders (
    id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    created_at DATE DEFAULT CURRENT_DATE NOT NULL,
    product_id VARCHAR2(100) NOT NULL,
    qty NUMBER NOT NULL,
    unit_price NUMBER NOT NULL,
    total_price NUMBER NOT NULL,
    user_id VARCHAR2(200) NOT NULL,
    order_id VARCHAR2(200) NOT NULL,
    CONSTRAINT order_id_unique UNIQUE (order_id)
);

COMMIT;

SELECT table_name FROM user_tables;

SELECT * FROM USERS;

SELECT * FROM catalog;

SELECT * FROM orders;

--TRUNCATE TABLE USERS;
--
--TRUNCATE TABLE catalog;

TRUNCATE TABLE ORDERS;


INSERT INTO CATALOG(product_id, product_name, stock, unit_price)
VALUES('CATALOG-0001', 'Berlin', 100, 1500);
INSERT INTO CATALOG(product_id, product_name, stock, unit_price)
VALUES('CATALOG-0002', 'Tokyo', 120, 900);
INSERT INTO CATALOG(product_id, product_name, stock, unit_price)
VALUES('CATALOG-0003', 'Stockholm', 150, 1200);
