select * from tb_cust_white_list;

create table users (
    id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    email VARCHAR2(50) NOT NULL,
    name VARCHAR2(50) NOT NULL,
    user_id VARCHAR2(200) NOT NULL,
    encrypted_pwd VARCHAR2(200) NOT NULL,
    CONSTRAINT email_unique UNIQUE (email),
    CONSTRAINT user_id_unique UNIQUE (user_id),
    CONSTRAINT encrypted_pwd_unique UNIQUE (encrypted_pwd)
);

COMMIT;

SELECT table_name FROM user_tables;

SELECT * FROM USERS;

TRUNCATE TABLE USERS;
